# Copyright (C) 2020-2026  Shihan Zhao and contributors
#
# This file is part of Mustard, an offline software framework for HEP experiments.
#
# Mustard is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Mustard is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Mustard. If not, see <https://www.gnu.org/licenses/>.

"""Generate GitHub Actions workflow YAML files and run-tests.sh from test-config.cfg.

Each line in test-config.cfg produces:
  - tooling/run-tests.sh (local serial test runner)
  - .github/workflows/<lowercase-test-names>-with-gcc.yml
  - .github/workflows/<lowercase-test-names>-with-clang.yml

Usage:
    python3 tooling/generate-test-scripts.py
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
CONFIG_FILE = os.path.join(SCRIPT_DIR, "test-config.cfg")
WORKFLOW_DIR = os.path.join(PROJECT_ROOT, ".github", "workflows")


def check_prerequisites():
    """Ensure the script is run from a directory containing .github/workflows."""
    if not os.path.isdir(WORKFLOW_DIR):
        print(
            "Error: .github/workflows directory not found. "
            "This script must be run from the project root directory "
            "that contains .github/workflows/.",
            file=sys.stderr,
        )
        sys.exit(1)


def parse_config():
    """Parse test-config.cfg and return a list of test sequences.

    Each sequence is a list of (exec_type, test_name) tuples,
    where exec_type is 'seqexec' or 'parexec'.
    """
    sequences = []
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Split by "->" to get ordered steps
            steps = [s.strip() for s in line.split("->")]
            parsed_steps = []
            for step in steps:
                parts = step.split()
                if len(parts) < 2:
                    print(
                        f"Warning: skipping malformed line: {line}", file=sys.stderr)
                    continue
                exec_type = parts[0]  # seqexec or parexec
                test_name = parts[1]
                parsed_steps.append((exec_type, test_name))
            if parsed_steps:
                sequences.append(parsed_steps)
    return sequences


def generate_run_tests_sh(sequences):
    """Generate a bash script (run-tests.sh) that executes all tests from config serially.

    Exits with the first non-zero return code encountered.
    """
    # Check whether any step uses parexec
    needs_parexec = any(
        exec_type == "parexec"
        for seq in sequences
        for exec_type, _ in seq
    )

    lines = [
        "#!/usr/bin/env bash",
        "# NOTE: This file is auto-generated by tooling/generate-test-scripts.py",
        "",
        "set -euo pipefail",
        "",
    ]

    if needs_parexec:
        lines.append('source parexec.sh')
        lines.append('')

    for steps in sequences:
        # Build a descriptive comment line
        names = "/".join(name for _, name in steps)
        lines.append(f'echo "Running {names}..."')
        for exec_type, test_name in steps:
            if exec_type == "seqexec":
                lines.append(f'echo "  -> ./MustardTest {test_name}"')
                lines.append(f'./MustardTest {test_name}')
            elif exec_type == "parexec":
                lines.append(
                    f'echo "  -> parexec ./MustardTest {test_name}"')
                lines.append(
                    f'parexec ./MustardTest {test_name}')
        lines.append('')

    lines.append('echo "All tests passed."')
    return "\n".join(lines) + "\n"


def generate_workflow_filename(test_names):
    """Generate the workflow filename from test names.

    e.g. ['TestMultiRDFEntryReader', 'TestMultiRDFEntryProcessor']
      -> 'testmultirdfentryreader-testmultirdfentryprocessor'
    """
    return "-".join(name.lower() for name in test_names)


def generate_workflow_name(test_names, compiler_name):
    """Generate the human-readable workflow name.

    e.g. (['TestMultiRDFEntryReader', 'TestMultiRDFEntryProcessor'], 'GCC')
      -> 'TestMultiRDFEntryReader/TestMultiRDFEntryProcessor (AMD64 GNU/Linux GCC)'
    """
    test_path = "/".join(test_names)
    return f"{test_path} (AMD64 GNU/Linux {compiler_name})"


def generate_build_step(compiler_c, compiler_cxx):
    """Generate the Build step YAML string for a given compiler."""
    return f"""      - name: Build
        run: |
          . /environment
          mkdir build && cd build
          cmake -G Ninja .. \\
            -DCMAKE_C_COMPILER={compiler_c} \\
            -DCMAKE_C_FLAGS='-march=native' \\
            -DCMAKE_CXX_COMPILER={compiler_cxx} \\
            -DCMAKE_CXX_FLAGS='-march=native' \\
            -DBUILD_TESTING=OFF \\
            -DMUSTARD_BUILD_TESTING=ON \\
            -DMUSTARD_FULL_UNITY_BUILD=ON
          ninja"""


def generate_run_step(steps):
    """Generate the Run step YAML string from a list of (exec_type, test_name) steps."""
    run_lines = []
    # Check if any step uses parexec
    needs_parexec = any(exec_type == "parexec" for exec_type, _ in steps)

    run_lines.append("      - name: Run " +
                     "/".join(name for _, name in steps))
    run_lines.append("        run: |")
    run_lines.append("          . /environment")
    if needs_parexec:
        run_lines.append("          source tooling/parexec.sh")
    run_lines.append("          cd build/test")
    for exec_type, test_name in steps:
        if exec_type == "seqexec":
            run_lines.append(f"          ./MustardTest {test_name}")
        elif exec_type == "parexec":
            run_lines.append(
                f"          parexec --use-hwthreads ./MustardTest {test_name}")
    return "\n".join(run_lines)


def generate_workflow_yaml(steps, compiler_c, compiler_cxx, compiler_name):
    """Generate the complete workflow YAML content."""
    test_names = [name for _, name in steps]
    filename = generate_workflow_filename(test_names)
    workflow_name = generate_workflow_name(test_names, compiler_name)
    job_id = f"{filename}-with-{compiler_name.lower()}"
    build_step = generate_build_step(compiler_c, compiler_cxx)
    run_step = generate_run_step(steps)

    yaml_content = f"""# NOTE: This file is auto-generated by tooling/generate-test-scripts.py

name: {workflow_name}

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/{filename}-with-{compiler_name.lower()}.yml"
      - "src/**"
      - "test/**"
      - "**/CMakeLists.txt"
      - "**.cmake"

  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/{filename}-with-{compiler_name.lower()}.yml"
      - "src/**"
      - "test/**"
      - "**/CMakeLists.txt"
      - "**.cmake"

permissions:
  contents: read

jobs:
  {job_id}:
    name: {workflow_name}
    timeout-minutes: 180
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - url: ghcr.io/zhao-shihan/rgb-docker:mpich
          - url: ghcr.io/zhao-shihan/rgb-docker:openmpi
    container: ${{{{ matrix.image.url }}}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

{build_step}

{run_step}
"""
    return yaml_content


def main():
    check_prerequisites()

    sequences = parse_config()

    if not sequences:
        print("No valid test sequences found in test-config.cfg.", file=sys.stderr)
        sys.exit(1)

    # Ensure the workflows directory exists
    os.makedirs(WORKFLOW_DIR, exist_ok=True)

    # Generate run-tests.sh in the script's own directory (tooling/)
    run_test_sh_path = os.path.join(SCRIPT_DIR, "run-tests.sh")
    run_test_sh_content = generate_run_tests_sh(sequences)
    with open(run_test_sh_path, "w", encoding="utf-8") as f:
        f.write(run_test_sh_content)
    os.chmod(run_test_sh_path, 0o755)
    print(f"Generated: {run_test_sh_path}")

    for steps in sequences:
        test_names = [name for _, name in steps]
        filename_base = generate_workflow_filename(test_names)

        # Generate GCC workflow
        gcc_yaml = generate_workflow_yaml(steps, "gcc", "g++", "GCC")
        gcc_filename = f"{filename_base}-with-gcc.yml"
        gcc_path = os.path.join(WORKFLOW_DIR, gcc_filename)
        with open(gcc_path, "w", encoding="utf-8") as f:
            f.write(gcc_yaml)
        print(f"Generated: {gcc_path}")

        # Generate Clang workflow
        clang_yaml = generate_workflow_yaml(steps, "clang", "clang++", "Clang")
        clang_filename = f"{filename_base}-with-clang.yml"
        clang_path = os.path.join(WORKFLOW_DIR, clang_filename)
        with open(clang_path, "w", encoding="utf-8") as f:
            f.write(clang_yaml)
        print(f"Generated: {clang_path}")


if __name__ == "__main__":
    main()
