# Copyright (C) 2020-2026  Shihan Zhao and contributors
#
# This file is part of Mustard, an offline software framework for HEP experiments.
#
# Mustard is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# Mustard is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Mustard. If not, see <https://www.gnu.org/licenses/>.

"""Generate GitHub Actions CI workflow and local test runner from test-config.cfg.

Generates:
  - .github/workflows/build-and-test-amd64-gnu-linux.yml   (single CI workflow: 4 builds + N test jobs)
  - tooling/run-tests.sh                                   (local serial test runner)

Design:
  - Build stage: 4 jobs (GCC/Clang x mpich/openmpi), each uploads a build artifact.
  - Test stage: ~100 jobs via matrix, each downloads the matching artifact and runs
    a single test sequence.  This avoids redundant builds and limits total builds to 4.

Usage:
    python3 tooling/generate-test-scripts.py
"""

import os
import sys
import textwrap

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
CONFIG_FILE = os.path.join(SCRIPT_DIR, "test-config.cfg")
WORKFLOW_DIR = os.path.join(PROJECT_ROOT, ".github", "workflows")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def check_prerequisites():
    """Ensure .github/workflows exists."""
    if not os.path.isdir(WORKFLOW_DIR):
        print(
            "Error: .github/workflows directory not found. "
            "This script must be run from the project root directory "
            "that contains .github/workflows/.",
            file=sys.stderr,
        )
        sys.exit(1)


def parse_config():
    """Parse test-config.cfg -> list of sequences.

    Each sequence is a list of (exec_type, test_name) tuples,
    where exec_type is 'seqexec' or 'parexec'.
    """
    sequences = []
    with open(CONFIG_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            steps = [s.strip() for s in line.split("->")]
            parsed = []
            for step in steps:
                parts = step.split()
                if len(parts) < 2:
                    print(f"Warning: skipping malformed line: {line}", file=sys.stderr)
                    continue
                parsed.append((parts[0], parts[1]))
            if parsed:
                sequences.append(parsed)
    return sequences


def test_sequence_key(steps):
    """Unique key for a test sequence, e.g. 'TestUniform' or
    'TestMultiRDFEntryReader-TestMultiRDFEntryProcessor-TestMultiRDFEntryProcessor'.
    """
    return "-".join(name for _, name in steps)


def test_sequence_commands(steps):
    """Return a list of bash command lines for a test sequence."""
    cmds = []
    for exec_type, test_name in steps:
        if exec_type == "seqexec":
            cmds.append(f"./MustardTest {test_name}")
        else:  # parexec
            cmds.append(f"parexec --use-hwthreads ./MustardTest {test_name}")
    return cmds


def needs_parexec(steps):
    """Whether any step in the sequence uses parexec."""
    return any(et == "parexec" for et, _ in steps)


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def generate_run_tests_sh(sequences):
    """Generate a local bash script that executes all test sequences serially."""
    has_parexec = any(needs_parexec(s) for s in sequences)

    lines = [
        "#!/usr/bin/env bash",
        "# NOTE: This file is auto-generated by tooling/generate-test-scripts.py",
        "",
        "set -euo pipefail",
        "",
    ]
    if has_parexec:
        lines.append('source parexec.sh')
        lines.append('')

    for steps in sequences:
        names = "/".join(name for _, name in steps)
        lines.append(f'echo "Running {names}..."')
        for exec_type, test_name in steps:
            if exec_type == "seqexec":
                lines.append(f'echo "  -> ./MustardTest {test_name}"')
                lines.append(f'./MustardTest {test_name}')
            else:
                lines.append(f'echo "  -> parexec ./MustardTest {test_name}"')
                lines.append(f'parexec ./MustardTest {test_name}')
        lines.append('')

    lines.append('echo "All tests passed."')
    return "\n".join(lines) + "\n"


def _indent(text, level):
    """Indent a multi-line string by *level* 2-space steps."""
    prefix = " " * (level * 2)
    return textwrap.indent(text, prefix)


def generate_build_and_test_yml(sequences):
    """Generate the single build-and-test-amd64-gnu-linux.yml workflow content.

    Build stage: 4 jobs (GCC/Clang x mpich/openmpi), each uploading a build artifact.
    Test stage:  N jobs via matrix (compiler x image x test-sequence), each
                downloading the matching artifact and running its test sequence.
    """
    # --- test matrix entries & case block ---
    test_keys = []
    case_lines = []
    for steps in sequences:
        key = test_sequence_key(steps)
        test_keys.append(key)
        cmds = test_sequence_commands(steps)
        case_lines.append(f'    "{key}")')
        for c in cmds:
            case_lines.append(f"      {c}")
        case_lines.append("      ;;")

    # Build without extra indentation; _indent() will add the correct amount
    test_matrix_json = "\n".join(f"- {k}" for k in test_keys)
    case_block = "\n".join(case_lines)

    yaml = f"""# NOTE: This file is auto-generated by tooling/generate-test-scripts.py

name: Build and Test (AMD64 GNU/Linux)

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/build-and-test-amd64-gnu-linux.yml"
      - "src/**"
      - "test/**"
      - "**/CMakeLists.txt"
      - "**.cmake"

  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/build-and-test-amd64-gnu-linux.yml"
      - "src/**"
      - "test/**"
      - "**/CMakeLists.txt"
      - "**.cmake"

permissions:
  contents: read

jobs:
  # -----------------------------------------------------------------------
  # Build stage -- 4 jobs total (GCC/Clang x mpich/openmpi)
  # -----------------------------------------------------------------------
  build:
    name: Build (AMD64 GNU/Linux, ${{{{ matrix.compiler.name }}}}, ${{{{ matrix.image.name }}}})
    timeout-minutes: 180
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {{ cc: gcc, cxx: g++, name: GCC }}
          - {{ cc: clang, cxx: clang++, name: Clang }}
        image:
          - {{ url: ghcr.io/zhao-shihan/rgb-docker:mpich, name: mpich }}
          - {{ url: ghcr.io/zhao-shihan/rgb-docker:openmpi, name: openmpi }}
    container: ${{{{ matrix.image.url }}}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build
        run: |
          . /environment
          mkdir build && cd build
          cmake -G Ninja .. \\
            -DCMAKE_C_COMPILER=${{{{ matrix.compiler.cc }}}} \\
            -DCMAKE_C_FLAGS='-march=native' \\
            -DCMAKE_CXX_COMPILER=${{{{ matrix.compiler.cxx }}}} \\
            -DCMAKE_CXX_FLAGS='-march=native' \\
            -DBUILD_TESTING=OFF \\
            -DMUSTARD_BUILD_TESTING=ON \\
            -DMUSTARD_FULL_UNITY_BUILD=ON \\
            -DMUSTARD_WERROR=ON
          ninja

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-amd64-gnu-linux-${{{{ matrix.compiler.name }}}}-${{{{ matrix.image.name }}}}
          path: |
            build/test/MustardTest
            build/test/parexec.sh
            build/test/*.root
            build/test/test_file_*/
          retention-days: 1

  # -----------------------------------------------------------------------
  # Test stage -- one job per (compiler, image, test sequence)
  # -----------------------------------------------------------------------
  test:
    name: ${{{{ matrix.test }}}} (AMD64 GNU/Linux, ${{{{ matrix.compiler.name }}}}, ${{{{ matrix.image.name }}}})
    needs: build
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {{ name: GCC }}
          - {{ name: Clang }}
        image:
          - {{ url: ghcr.io/zhao-shihan/rgb-docker:mpich, name: mpich }}
          - {{ url: ghcr.io/zhao-shihan/rgb-docker:openmpi, name: openmpi }}
        test:
{_indent(test_matrix_json, 5)}
    container: ${{{{ matrix.image.url }}}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code (for test data and scripts)
        uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-amd64-gnu-linux-${{{{ matrix.compiler.name }}}}-${{{{ matrix.image.name }}}}
          path: build/test

      - name: Run test sequence
        run: |
          . /environment
          chmod +x build/test/MustardTest build/test/parexec.sh 2>/dev/null || true
          source tooling/parexec.sh 2>/dev/null || true
          cd build/test
          case "${{{{ matrix.test }}}}" in
{_indent(case_block, 6)}
          esac
"""
    return yaml


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    check_prerequisites()

    sequences = parse_config()
    if not sequences:
        print("No valid test sequences found in test-config.cfg.", file=sys.stderr)
        sys.exit(1)

    # Ensure output directories exist
    os.makedirs(WORKFLOW_DIR, exist_ok=True)

    # 1. Local test runner script
    run_sh_path = os.path.join(SCRIPT_DIR, "run-tests.sh")
    run_sh = generate_run_tests_sh(sequences)
    with open(run_sh_path, "w", encoding="utf-8") as f:
        f.write(run_sh)
    os.chmod(run_sh_path, 0o755)
    print(f"Generated: {run_sh_path}")

    # 2. Single CI workflow
    workflow_path = os.path.join(WORKFLOW_DIR, "build-and-test-amd64-gnu-linux.yml")
    workflow_yml = generate_build_and_test_yml(sequences)
    with open(workflow_path, "w", encoding="utf-8") as f:
        f.write(workflow_yml)
    print(f"Generated: {workflow_path}")
    print(f"  -> {len(sequences)} test sequences x 4 configs = {len(sequences)*4} test jobs")


if __name__ == "__main__":
    main()
