#!/usr/bin/env bash
# NOTE: This file is auto-generated by tooling/generate-test-scripts.py

set -euo pipefail

source parexec.sh

echo "Running TestCLHEPXMT1993732/TestCLHEPXMT1993764/TestCLHEPXXoshiro256StarStar/TestCLHEPXXoshiro512StarStar..."
echo "  -> ./MustardTest TestCLHEPXMT1993732"
./MustardTest TestCLHEPXMT1993732
echo "  -> ./MustardTest TestCLHEPXMT1993764"
./MustardTest TestCLHEPXMT1993764
echo "  -> ./MustardTest TestCLHEPXXoshiro256StarStar"
./MustardTest TestCLHEPXXoshiro256StarStar
echo "  -> ./MustardTest TestCLHEPXXoshiro512StarStar"
./MustardTest TestCLHEPXXoshiro512StarStar

echo "Running TestCreateTemporaryFile/TestCreateTemporaryFile..."
echo "  -> ./MustardTest TestCreateTemporaryFile"
./MustardTest TestCreateTemporaryFile
echo "  -> parexec ./MustardTest TestCreateTemporaryFile"
parexec ./MustardTest TestCreateTemporaryFile

echo "Running TestEstimate0/TestEstimate1/TestEstimate2/TestEstimate3/TestEstimate4/TestEstimate5/TestEstimate6/TestEstimate7/TestEstimate8/TestEstimate9/TestEstimate10/TestEstimate11/TestEstimate12/TestEstimate13/TestEstimate14/TestEstimate15/TestEstimate16/TestEstimate17/TestEstimate18/TestEstimate19/TestEstimate20/TestEstimate21/TestEstimate22/TestEstimate23/TestEstimate24/TestEstimate25/TestEstimate26/TestEstimate27/TestEstimate28/TestEstimate29/TestEstimate30/TestEstimate31/TestEstimate32/TestEstimate33/TestEstimate34/TestEstimate35/TestEstimate36/TestEstimate37..."
echo "  -> ./MustardTest TestEstimate0"
./MustardTest TestEstimate0
echo "  -> ./MustardTest TestEstimate1"
./MustardTest TestEstimate1
echo "  -> ./MustardTest TestEstimate2"
./MustardTest TestEstimate2
echo "  -> ./MustardTest TestEstimate3"
./MustardTest TestEstimate3
echo "  -> ./MustardTest TestEstimate4"
./MustardTest TestEstimate4
echo "  -> ./MustardTest TestEstimate5"
./MustardTest TestEstimate5
echo "  -> ./MustardTest TestEstimate6"
./MustardTest TestEstimate6
echo "  -> ./MustardTest TestEstimate7"
./MustardTest TestEstimate7
echo "  -> ./MustardTest TestEstimate8"
./MustardTest TestEstimate8
echo "  -> ./MustardTest TestEstimate9"
./MustardTest TestEstimate9
echo "  -> ./MustardTest TestEstimate10"
./MustardTest TestEstimate10
echo "  -> ./MustardTest TestEstimate11"
./MustardTest TestEstimate11
echo "  -> ./MustardTest TestEstimate12"
./MustardTest TestEstimate12
echo "  -> ./MustardTest TestEstimate13"
./MustardTest TestEstimate13
echo "  -> ./MustardTest TestEstimate14"
./MustardTest TestEstimate14
echo "  -> ./MustardTest TestEstimate15"
./MustardTest TestEstimate15
echo "  -> ./MustardTest TestEstimate16"
./MustardTest TestEstimate16
echo "  -> ./MustardTest TestEstimate17"
./MustardTest TestEstimate17
echo "  -> ./MustardTest TestEstimate18"
./MustardTest TestEstimate18
echo "  -> ./MustardTest TestEstimate19"
./MustardTest TestEstimate19
echo "  -> ./MustardTest TestEstimate20"
./MustardTest TestEstimate20
echo "  -> ./MustardTest TestEstimate21"
./MustardTest TestEstimate21
echo "  -> ./MustardTest TestEstimate22"
./MustardTest TestEstimate22
echo "  -> ./MustardTest TestEstimate23"
./MustardTest TestEstimate23
echo "  -> ./MustardTest TestEstimate24"
./MustardTest TestEstimate24
echo "  -> ./MustardTest TestEstimate25"
./MustardTest TestEstimate25
echo "  -> ./MustardTest TestEstimate26"
./MustardTest TestEstimate26
echo "  -> ./MustardTest TestEstimate27"
./MustardTest TestEstimate27
echo "  -> ./MustardTest TestEstimate28"
./MustardTest TestEstimate28
echo "  -> ./MustardTest TestEstimate29"
./MustardTest TestEstimate29
echo "  -> ./MustardTest TestEstimate30"
./MustardTest TestEstimate30
echo "  -> ./MustardTest TestEstimate31"
./MustardTest TestEstimate31
echo "  -> ./MustardTest TestEstimate32"
./MustardTest TestEstimate32
echo "  -> ./MustardTest TestEstimate33"
./MustardTest TestEstimate33
echo "  -> ./MustardTest TestEstimate34"
./MustardTest TestEstimate34
echo "  -> ./MustardTest TestEstimate35"
./MustardTest TestEstimate35
echo "  -> ./MustardTest TestEstimate36"
./MustardTest TestEstimate36
echo "  -> ./MustardTest TestEstimate37"
./MustardTest TestEstimate37

echo "Running TestExecutor/TestExecutor..."
echo "  -> ./MustardTest TestExecutor"
./MustardTest TestExecutor
echo "  -> parexec ./MustardTest TestExecutor"
parexec ./MustardTest TestExecutor

echo "Running TestExecutorSequential..."
echo "  -> ./MustardTest TestExecutorSequential"
./MustardTest TestExecutorSequential

echo "Running TestFieldTypeName..."
echo "  -> ./MustardTest TestFieldTypeName"
./MustardTest TestFieldTypeName

echo "Running TestFile/TestFile..."
echo "  -> ./MustardTest TestFile"
./MustardTest TestFile
echo "  -> parexec ./MustardTest TestFile"
parexec ./MustardTest TestFile

echo "Running TestLinePointPOCA/TestLineLinePOCA/TestHelixAxisPOCA/TestHelixPointPOCA/TestHelixLinePOCA..."
echo "  -> ./MustardTest TestLinePointPOCA"
./MustardTest TestLinePointPOCA
echo "  -> ./MustardTest TestLineLinePOCA"
./MustardTest TestLineLinePOCA
echo "  -> ./MustardTest TestHelixAxisPOCA"
./MustardTest TestHelixAxisPOCA
echo "  -> ./MustardTest TestHelixPointPOCA"
./MustardTest TestHelixPointPOCA
echo "  -> ./MustardTest TestHelixLinePOCA"
./MustardTest TestHelixLinePOCA

echo "Running TestMT1993732/TestMT1993764..."
echo "  -> ./MustardTest TestMT1993732"
./MustardTest TestMT1993732
echo "  -> ./MustardTest TestMT1993764"
./MustardTest TestMT1993764

echo "Running TestMultiRDFEntryReader/TestMultiRDFEntryProcessor/TestMultiRDFEntryProcessor..."
echo "  -> ./MustardTest TestMultiRDFEntryReader"
./MustardTest TestMultiRDFEntryReader
echo "  -> ./MustardTest TestMultiRDFEntryProcessor"
./MustardTest TestMultiRDFEntryProcessor
echo "  -> parexec ./MustardTest TestMultiRDFEntryProcessor"
parexec ./MustardTest TestMultiRDFEntryProcessor

echo "Running TestMultiRDFEventReader/TestMultiRDFEventProcessor/TestMultiRDFEventProcessor..."
echo "  -> ./MustardTest TestMultiRDFEventReader"
./MustardTest TestMultiRDFEventReader
echo "  -> ./MustardTest TestMultiRDFEventProcessor"
./MustardTest TestMultiRDFEventProcessor
echo "  -> parexec ./MustardTest TestMultiRDFEventProcessor"
parexec ./MustardTest TestMultiRDFEventProcessor

echo "Running TestPassiveSingleton/TestPassiveSingleton..."
echo "  -> ./MustardTest TestPassiveSingleton"
./MustardTest TestPassiveSingleton
echo "  -> parexec ./MustardTest TestPassiveSingleton"
parexec ./MustardTest TestPassiveSingleton

echo "Running TestPhaseSpaceGenerator/TestPhaseSpaceGenerator..."
echo "  -> ./MustardTest TestPhaseSpaceGenerator"
./MustardTest TestPhaseSpaceGenerator
echo "  -> parexec ./MustardTest TestPhaseSpaceGenerator"
parexec ./MustardTest TestPhaseSpaceGenerator

echo "Running TestRandomNumberDistribution/TestGaussian/TestUniform..."
echo "  -> ./MustardTest TestRandomNumberDistribution"
./MustardTest TestRandomNumberDistribution
echo "  -> ./MustardTest TestGaussian"
./MustardTest TestGaussian
echo "  -> ./MustardTest TestUniform"
./MustardTest TestUniform

echo "Running TestSingleRDFEntryReader/TestSingleRDFEntryProcessor/TestSingleRDFEntryProcessor..."
echo "  -> ./MustardTest TestSingleRDFEntryReader"
./MustardTest TestSingleRDFEntryReader
echo "  -> ./MustardTest TestSingleRDFEntryProcessor"
./MustardTest TestSingleRDFEntryProcessor
echo "  -> parexec ./MustardTest TestSingleRDFEntryProcessor"
parexec ./MustardTest TestSingleRDFEntryProcessor

echo "Running TestSingleRDFEventReader/TestSingleRDFEventProcessor/TestSingleRDFEventProcessor..."
echo "  -> ./MustardTest TestSingleRDFEventReader"
./MustardTest TestSingleRDFEventReader
echo "  -> ./MustardTest TestSingleRDFEventProcessor"
./MustardTest TestSingleRDFEventProcessor
echo "  -> parexec ./MustardTest TestSingleRDFEventProcessor"
parexec ./MustardTest TestSingleRDFEventProcessor

echo "Running TestSingleton/TestSingleton..."
echo "  -> ./MustardTest TestSingleton"
./MustardTest TestSingleton
echo "  -> parexec ./MustardTest TestSingleton"
parexec ./MustardTest TestSingleton

echo "Running TestStatistic0/TestStatistic1/TestStatistic2/TestStatistic3/TestStatistic4/TestStatistic5/TestStatistic6/TestStatistic7/TestStatistic8/TestStatistic9/TestStatistic10..."
echo "  -> ./MustardTest TestStatistic0"
./MustardTest TestStatistic0
echo "  -> ./MustardTest TestStatistic1"
./MustardTest TestStatistic1
echo "  -> ./MustardTest TestStatistic2"
./MustardTest TestStatistic2
echo "  -> ./MustardTest TestStatistic3"
./MustardTest TestStatistic3
echo "  -> ./MustardTest TestStatistic4"
./MustardTest TestStatistic4
echo "  -> ./MustardTest TestStatistic5"
./MustardTest TestStatistic5
echo "  -> ./MustardTest TestStatistic6"
./MustardTest TestStatistic6
echo "  -> ./MustardTest TestStatistic7"
./MustardTest TestStatistic7
echo "  -> ./MustardTest TestStatistic8"
./MustardTest TestStatistic8
echo "  -> ./MustardTest TestStatistic9"
./MustardTest TestStatistic9
echo "  -> ./MustardTest TestStatistic10"
./MustardTest TestStatistic10

echo "Running TestVectorConcept..."
echo "  -> ./MustardTest TestVectorConcept"
./MustardTest TestVectorConcept

echo "Running TestXoshiro256Plus/TestXoshiro256PlusPlus/TestXoshiro256StarStar/TestXoshiro512Plus/TestXoshiro512PlusPlus/TestXoshiro512StarStar..."
echo "  -> ./MustardTest TestXoshiro256Plus"
./MustardTest TestXoshiro256Plus
echo "  -> ./MustardTest TestXoshiro256PlusPlus"
./MustardTest TestXoshiro256PlusPlus
echo "  -> ./MustardTest TestXoshiro256StarStar"
./MustardTest TestXoshiro256StarStar
echo "  -> ./MustardTest TestXoshiro512Plus"
./MustardTest TestXoshiro512Plus
echo "  -> ./MustardTest TestXoshiro512PlusPlus"
./MustardTest TestXoshiro512PlusPlus
echo "  -> ./MustardTest TestXoshiro512StarStar"
./MustardTest TestXoshiro512StarStar

echo "All tests passed."
