#!/usr/bin/env bash
# NOTE: This file is auto-generated by tooling/generate-test-scripts.py

set -euo pipefail

source parexec.sh

echo "Running TestCLHEPXMT1993732..."
echo "  -> ./MustardTest TestCLHEPXMT1993732"
./MustardTest TestCLHEPXMT1993732

echo "Running TestCLHEPXMT1993764..."
echo "  -> ./MustardTest TestCLHEPXMT1993764"
./MustardTest TestCLHEPXMT1993764

echo "Running TestCLHEPXXoshiro256StarStar..."
echo "  -> ./MustardTest TestCLHEPXXoshiro256StarStar"
./MustardTest TestCLHEPXXoshiro256StarStar

echo "Running TestCLHEPXXoshiro512StarStar..."
echo "  -> ./MustardTest TestCLHEPXXoshiro512StarStar"
./MustardTest TestCLHEPXXoshiro512StarStar

echo "Running TestCreateTemporaryFile/TestCreateTemporaryFile..."
echo "  -> ./MustardTest TestCreateTemporaryFile"
./MustardTest TestCreateTemporaryFile
echo "  -> parexec ./MustardTest TestCreateTemporaryFile"
parexec ./MustardTest TestCreateTemporaryFile

echo "Running TestExecutor/TestExecutor..."
echo "  -> ./MustardTest TestExecutor"
./MustardTest TestExecutor
echo "  -> parexec ./MustardTest TestExecutor"
parexec ./MustardTest TestExecutor

echo "Running TestExecutorSequential..."
echo "  -> ./MustardTest TestExecutorSequential"
./MustardTest TestExecutorSequential

echo "Running TestFieldTypeName..."
echo "  -> ./MustardTest TestFieldTypeName"
./MustardTest TestFieldTypeName

echo "Running TestFile/TestFile..."
echo "  -> ./MustardTest TestFile"
./MustardTest TestFile
echo "  -> parexec ./MustardTest TestFile"
parexec ./MustardTest TestFile

echo "Running TestGaussian..."
echo "  -> ./MustardTest TestGaussian"
./MustardTest TestGaussian

echo "Running TestMT1993732..."
echo "  -> ./MustardTest TestMT1993732"
./MustardTest TestMT1993732

echo "Running TestMT1993764..."
echo "  -> ./MustardTest TestMT1993764"
./MustardTest TestMT1993764

echo "Running TestMultiRDFEntryReader/TestMultiRDFEntryProcessor/TestMultiRDFEntryProcessor..."
echo "  -> ./MustardTest TestMultiRDFEntryReader"
./MustardTest TestMultiRDFEntryReader
echo "  -> ./MustardTest TestMultiRDFEntryProcessor"
./MustardTest TestMultiRDFEntryProcessor
echo "  -> parexec ./MustardTest TestMultiRDFEntryProcessor"
parexec ./MustardTest TestMultiRDFEntryProcessor

echo "Running TestMultiRDFEventReader/TestMultiRDFEventProcessor/TestMultiRDFEventProcessor..."
echo "  -> ./MustardTest TestMultiRDFEventReader"
./MustardTest TestMultiRDFEventReader
echo "  -> ./MustardTest TestMultiRDFEventProcessor"
./MustardTest TestMultiRDFEventProcessor
echo "  -> parexec ./MustardTest TestMultiRDFEventProcessor"
parexec ./MustardTest TestMultiRDFEventProcessor

echo "Running TestPassiveSingleton/TestPassiveSingleton..."
echo "  -> ./MustardTest TestPassiveSingleton"
./MustardTest TestPassiveSingleton
echo "  -> parexec ./MustardTest TestPassiveSingleton"
parexec ./MustardTest TestPassiveSingleton

echo "Running TestPhaseSpaceGenerator/TestPhaseSpaceGenerator..."
echo "  -> ./MustardTest TestPhaseSpaceGenerator"
./MustardTest TestPhaseSpaceGenerator
echo "  -> parexec ./MustardTest TestPhaseSpaceGenerator"
parexec ./MustardTest TestPhaseSpaceGenerator

echo "Running TestRandomNumberDistribution..."
echo "  -> ./MustardTest TestRandomNumberDistribution"
./MustardTest TestRandomNumberDistribution

echo "Running TestSingleRDFEntryReader/TestSingleRDFEntryProcessor/TestSingleRDFEntryProcessor..."
echo "  -> ./MustardTest TestSingleRDFEntryReader"
./MustardTest TestSingleRDFEntryReader
echo "  -> ./MustardTest TestSingleRDFEntryProcessor"
./MustardTest TestSingleRDFEntryProcessor
echo "  -> parexec ./MustardTest TestSingleRDFEntryProcessor"
parexec ./MustardTest TestSingleRDFEntryProcessor

echo "Running TestSingleRDFEventReader/TestSingleRDFEventProcessor/TestSingleRDFEventProcessor..."
echo "  -> ./MustardTest TestSingleRDFEventReader"
./MustardTest TestSingleRDFEventReader
echo "  -> ./MustardTest TestSingleRDFEventProcessor"
./MustardTest TestSingleRDFEventProcessor
echo "  -> parexec ./MustardTest TestSingleRDFEventProcessor"
parexec ./MustardTest TestSingleRDFEventProcessor

echo "Running TestSingleton/TestSingleton..."
echo "  -> ./MustardTest TestSingleton"
./MustardTest TestSingleton
echo "  -> parexec ./MustardTest TestSingleton"
parexec ./MustardTest TestSingleton

echo "Running TestUniform..."
echo "  -> ./MustardTest TestUniform"
./MustardTest TestUniform

echo "Running TestVectorConcept..."
echo "  -> ./MustardTest TestVectorConcept"
./MustardTest TestVectorConcept

echo "Running TestXoshiro256Plus..."
echo "  -> ./MustardTest TestXoshiro256Plus"
./MustardTest TestXoshiro256Plus

echo "Running TestXoshiro256PlusPlus..."
echo "  -> ./MustardTest TestXoshiro256PlusPlus"
./MustardTest TestXoshiro256PlusPlus

echo "Running TestXoshiro256StarStar..."
echo "  -> ./MustardTest TestXoshiro256StarStar"
./MustardTest TestXoshiro256StarStar

echo "Running TestXoshiro512Plus..."
echo "  -> ./MustardTest TestXoshiro512Plus"
./MustardTest TestXoshiro512Plus

echo "Running TestXoshiro512PlusPlus..."
echo "  -> ./MustardTest TestXoshiro512PlusPlus"
./MustardTest TestXoshiro512PlusPlus

echo "Running TestXoshiro512StarStar..."
echo "  -> ./MustardTest TestXoshiro512StarStar"
./MustardTest TestXoshiro512StarStar

echo "All tests passed."
